### ISSUE TITLE
sort failing with new release

### ISSUE THREAD

**Issue by bguise987** [bulv1ne/python-style-check#2]
When running this action, I'm now seeing an error with my builds.

I believe this is caused by this action using
`isort --check-only --diff --quiet`

Whereas isort 5.4.2 produces the following output when run this way:

> Nothing to do: no files or paths have have been passed in!
> 
> Try one of the following:
> 
>     `isort .` - sort all Python files, starting from the current directory, recursively.
>     `isort . --interactive` - Do the same, but ask before making any changes.
>     `isort . --check --diff` - Check to see if imports are correctly sorted within this project.
>     `isort --help` - In-depth information about isort's available command-line options.
> 
> Visit https://timothycrosley.github.io/isort/ for complete information about how to use isort.
> 
> Error: arguments passed in without any paths or content.

I believe the solution is to change the isort command to the following:
`isort . --check --diff`

**Comment by bulv1ne** [comment]
Closing this because #3 is merged :)
